env:
  CI_ALLOW_ROOT: '1'
  CI_CONFIG: ./ci.nix
  CI_PLATFORM: gh-actions
jobs:
  all:
    name: input-linux-all
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      name: git clone
      uses: actions/checkout@v3
      with:
        submodules: true
    - id: nix-install
      name: nix install
      uses: arcnmx/ci/actions/nix/install@v0.6
    - id: ci-setup
      name: nix setup
      uses: arcnmx/ci/actions/nix/run@v0.6
      with:
        attrs: ci.job.all.run.setup
        quiet: false
    - id: ci-dirty
      name: nix test dirty
      uses: arcnmx/ci/actions/nix/run@v0.6
      with:
        attrs: ci.job.all.run.test
        command: ci-build-dirty
        quiet: false
        stdout: ${{ runner.temp }}/ci.build.dirty
    - id: ci-test
      name: nix test build
      uses: arcnmx/ci/actions/nix/run@v0.6
      with:
        attrs: ci.job.all.run.test
        command: ci-build-realise
        ignore-exit-code: true
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.dirty
    - env:
        CI_EXIT_CODE: ${{ steps.ci-test.outputs.exit-code }}
      id: ci-summary
      name: nix test results
      uses: arcnmx/ci/actions/nix/run@v0.6
      with:
        attrs: ci.job.all.run.test
        command: ci-build-summarise
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.dirty
        stdout: ${{ runner.temp }}/ci.build.cache
    - env:
        CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
      id: ci-cache
      if: always()
      name: nix test cache
      uses: arcnmx/ci/actions/nix/run@v0.6
      with:
        attrs: ci.job.all.run.test
        command: ci-build-cache
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.cache
  ci-check:
    name: input-linux check
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      name: git clone
      uses: actions/checkout@v3
      with:
        submodules: true
    - id: nix-install
      name: nix install
      uses: arcnmx/ci/actions/nix/install@v0.6
    - id: ci-action-build
      name: nix build ci.gh-actions.configFile
      uses: arcnmx/ci/actions/nix/build@v0.6
      with:
        attrs: ci.gh-actions.configFile
        out-link: .ci/workflow.yml
    - id: ci-action-compare
      name: gh-actions compare
      uses: arcnmx/ci/actions/nix/run@v0.6
      with:
        args: -u .github/workflows/input-linux.yml .ci/workflow.yml
        attrs: nixpkgs.diffutils
        command: diff
  default:
    name: input-linux-default
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      name: git clone
      uses: actions/checkout@v3
      with:
        submodules: true
    - id: nix-install
      name: nix install
      uses: arcnmx/ci/actions/nix/install@v0.6
    - id: ci-setup
      name: nix setup
      uses: arcnmx/ci/actions/nix/run@v0.6
      with:
        attrs: ci.job.default.run.setup
        quiet: false
    - id: ci-dirty
      name: nix test dirty
      uses: arcnmx/ci/actions/nix/run@v0.6
      with:
        attrs: ci.job.default.run.test
        command: ci-build-dirty
        quiet: false
        stdout: ${{ runner.temp }}/ci.build.dirty
    - id: ci-test
      name: nix test build
      uses: arcnmx/ci/actions/nix/run@v0.6
      with:
        attrs: ci.job.default.run.test
        command: ci-build-realise
        ignore-exit-code: true
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.dirty
    - env:
        CI_EXIT_CODE: ${{ steps.ci-test.outputs.exit-code }}
      id: ci-summary
      name: nix test results
      uses: arcnmx/ci/actions/nix/run@v0.6
      with:
        attrs: ci.job.default.run.test
        command: ci-build-summarise
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.dirty
        stdout: ${{ runner.temp }}/ci.build.cache
    - env:
        CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
      id: ci-cache
      if: always()
      name: nix test cache
      uses: arcnmx/ci/actions/nix/run@v0.6
      with:
        attrs: ci.job.default.run.test
        command: ci-build-cache
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.cache
  serde:
    name: input-linux-serde
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      name: git clone
      uses: actions/checkout@v3
      with:
        submodules: true
    - id: nix-install
      name: nix install
      uses: arcnmx/ci/actions/nix/install@v0.6
    - id: ci-setup
      name: nix setup
      uses: arcnmx/ci/actions/nix/run@v0.6
      with:
        attrs: ci.job.serde.run.setup
        quiet: false
    - id: ci-dirty
      name: nix test dirty
      uses: arcnmx/ci/actions/nix/run@v0.6
      with:
        attrs: ci.job.serde.run.test
        command: ci-build-dirty
        quiet: false
        stdout: ${{ runner.temp }}/ci.build.dirty
    - id: ci-test
      name: nix test build
      uses: arcnmx/ci/actions/nix/run@v0.6
      with:
        attrs: ci.job.serde.run.test
        command: ci-build-realise
        ignore-exit-code: true
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.dirty
    - env:
        CI_EXIT_CODE: ${{ steps.ci-test.outputs.exit-code }}
      id: ci-summary
      name: nix test results
      uses: arcnmx/ci/actions/nix/run@v0.6
      with:
        attrs: ci.job.serde.run.test
        command: ci-build-summarise
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.dirty
        stdout: ${{ runner.temp }}/ci.build.cache
    - env:
        CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
      id: ci-cache
      if: always()
      name: nix test cache
      uses: arcnmx/ci/actions/nix/run@v0.6
      with:
        attrs: ci.job.serde.run.test
        command: ci-build-cache
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.cache
  tokio-util-0_6:
    name: input-linux-tokio-util-0_6
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      name: git clone
      uses: actions/checkout@v3
      with:
        submodules: true
    - id: nix-install
      name: nix install
      uses: arcnmx/ci/actions/nix/install@v0.6
    - id: ci-setup
      name: nix setup
      uses: arcnmx/ci/actions/nix/run@v0.6
      with:
        attrs: ci.job.tokio-util-0_6.run.setup
        quiet: false
    - id: ci-dirty
      name: nix test dirty
      uses: arcnmx/ci/actions/nix/run@v0.6
      with:
        attrs: ci.job.tokio-util-0_6.run.test
        command: ci-build-dirty
        quiet: false
        stdout: ${{ runner.temp }}/ci.build.dirty
    - id: ci-test
      name: nix test build
      uses: arcnmx/ci/actions/nix/run@v0.6
      with:
        attrs: ci.job.tokio-util-0_6.run.test
        command: ci-build-realise
        ignore-exit-code: true
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.dirty
    - env:
        CI_EXIT_CODE: ${{ steps.ci-test.outputs.exit-code }}
      id: ci-summary
      name: nix test results
      uses: arcnmx/ci/actions/nix/run@v0.6
      with:
        attrs: ci.job.tokio-util-0_6.run.test
        command: ci-build-summarise
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.dirty
        stdout: ${{ runner.temp }}/ci.build.cache
    - env:
        CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
      id: ci-cache
      if: always()
      name: nix test cache
      uses: arcnmx/ci/actions/nix/run@v0.6
      with:
        attrs: ci.job.tokio-util-0_6.run.test
        command: ci-build-cache
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.cache
  tokio-util-0_7:
    name: input-linux-tokio-util-0_7
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      name: git clone
      uses: actions/checkout@v3
      with:
        submodules: true
    - id: nix-install
      name: nix install
      uses: arcnmx/ci/actions/nix/install@v0.6
    - id: ci-setup
      name: nix setup
      uses: arcnmx/ci/actions/nix/run@v0.6
      with:
        attrs: ci.job.tokio-util-0_7.run.setup
        quiet: false
    - id: ci-dirty
      name: nix test dirty
      uses: arcnmx/ci/actions/nix/run@v0.6
      with:
        attrs: ci.job.tokio-util-0_7.run.test
        command: ci-build-dirty
        quiet: false
        stdout: ${{ runner.temp }}/ci.build.dirty
    - id: ci-test
      name: nix test build
      uses: arcnmx/ci/actions/nix/run@v0.6
      with:
        attrs: ci.job.tokio-util-0_7.run.test
        command: ci-build-realise
        ignore-exit-code: true
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.dirty
    - env:
        CI_EXIT_CODE: ${{ steps.ci-test.outputs.exit-code }}
      id: ci-summary
      name: nix test results
      uses: arcnmx/ci/actions/nix/run@v0.6
      with:
        attrs: ci.job.tokio-util-0_7.run.test
        command: ci-build-summarise
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.dirty
        stdout: ${{ runner.temp }}/ci.build.cache
    - env:
        CACHIX_SIGNING_KEY: ${{ secrets.CACHIX_SIGNING_KEY }}
      id: ci-cache
      if: always()
      name: nix test cache
      uses: arcnmx/ci/actions/nix/run@v0.6
      with:
        attrs: ci.job.tokio-util-0_7.run.test
        command: ci-build-cache
        quiet: false
        stdin: ${{ runner.temp }}/ci.build.cache
name: input-linux
'on':
- push
- pull_request
